"""
提示模板模块
"""

from .system_prompts import SYSTEM_PROMPT
from .task_prompts import (
    QUERY_ANALYSIS_PROMPT,
    ANSWER_GENERATION_PROMPT,
    ANSWER_EVALUATION_PROMPT,
    QUERY_REWRITING_PROMPT,
    CONTEXT_FILTERING_PROMPT,
    GENERATOR_USER_PROMPT_TEMPLATE
)

__all__ = [
    "SYSTEM_PROMPT",
    "QUERY_ANALYSIS_PROMPT",
    "ANSWER_GENERATION_PROMPT",
    "ANSWER_EVALUATION_PROMPT",
    "QUERY_REWRITING_PROMPT",
    "CONTEXT_FILTERING_PROMPT"
]
